dependencies = []
description = "Simple package manager for Luau"
files = ["*"]
keywords = [""]
main = { bin = "./test.luau" }
name = "cmder"
owner = "0xjwlabs"
version = "0.1.1"

[build_config]
name = "cmder"

[build_config.release]
debug_level = 0
optimisation_level = 2