return {
    cli = {
        title =  "#89b4fa",
        text = "#cdd6f4",
        category = "#f9e2af"
    },
    command = {
        definition = "#f5e0dc",
        description = "#cdd6f4",
        argument = "#cba6f7",
        option = "#89b4fa",
        category = "#fab387"
    },
    primary = "#89b4fa",
    secondary = "#f38ba8",
    success = "green",
    warning = "yellow",
    error = "#f38ba8"
}