return {
    acid = {
        cli = {
            title = 'yellow',
            text = 'white',
            category = 'yellow',
        },
        command = {
            definition = 'green',
            description = 'white',
            argument = 'yellow',
            option = 'yellow',
            category = 'red',
        },
        primary = 'green',
        secondary = 'red',
        success = 'green',
        warning = 'yellow',
        error = 'red',
    },
    catppuccin = {
        cli = {
            title = {
                color = '#89b4fa',
                style = 'bold'
            },
            text = '#cdd6f4',
            category = '#f9e2af',
        },
        command = {
            definition = '#f5e0dc',
            description = '#cdd6f4',
            argument = '#cba6f7',
            option = '#89b4fa',
            category = '#fab387',
        },
        primary = '#89b4fa',
        secondary = '#f38ba8',
        success = 'green',
        warning = 'yellow',
        error = '#f38ba8',
    },
    default = {
        cli = {
            title = 'red',
            text = 'white',
            category = 'yellow',
        },
        command = {
            definition = 'green',
            description = 'white',
            argument = 'red',
            option = 'red',
            category = 'yellow',
        },
        primary = 'green',
        secondary = 'yellow',
        success = 'green',
        warning = 'yellow',
        error = 'red',
    },
}
